name: home_brigadier
version: 0.1.23+24
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'
  flutter: "3.19.6"

dependencies: 
  cupertino_icons:
  get:
  get_storage:
  flutter_svg:
  flutter_pin_code_fields:
  table_calendar:
  buttons_tabbar: ^1.3.12
  expandable_text:
  cached_network_image:
  carousel_slider:
  location:
  dio:
  image_picker:
  geolocator:
  geocoding:
  google_maps_flutter:
  shimmer:
  font_awesome_flutter:
  intl:
  url_launcher:
  showcaseview:
  flutter_contacts:
  connectivity_plus:
  http:
  flutter_google_places:
  lottie:
  video_player:
  flutter_stripe:
  marquee:
  flutter_dotenv:
  dartx:
  firebase_core:
  firebase_messaging:
  flutter_local_notifications:
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints:
  flutter_launcher_icons:
  logger:
  flutter_test: 
    sdk: flutter

flutter_launcher_icons: 
  android: ic_launcher
  image_path: assets/launcher/ic_launcher.png
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
    - assets/video/
    - .env
    - assets/launcher/
  uses-material-design: true

